name: Docker Image CD

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t asafecode/api-myrecipebook:latest .
      
    - name: Login to DockerHub
      run: |
        dckr_pat_0kabDvJ5V_0qMfkovmoLKKjaVd4 | docker login -u asafecode --password-stdin
        

    - name: Push the Docker image
      run: |
        docker push asafecode/api-myrecipebook:latest
      
        
    
