name: Docker Image CD

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        
      run: docker build -t "$DOCKERHUB_USERNAME"/api-myrecipebook:latest .
      
    - name: Login to DockerHub
      run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        
    - name: Push the Docker image
      run: docker push "$DOCKERHUB_USERNAME"/api-myrecipebook:latest
        
      
        
    
